### ISSUE TITLE
feat: add high level diagram / chart

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/docs#104]
https://github.com/cowprotocol/docs-v2/blob/cd2883a75475f366c4628ac653c74eb6faf5cb66/docs/cow-protocol/concepts/batch-auctions/how-batch-auctions-work.md?plain=1#L11

This looks like a very implementation specific sequence diagram of our low level off-chain components. In a file that attempts to document the high level workings of a batch auction, we should use something less technical and more high level.

**Comment by mfw78** [comment]
The implementation specific chart was removed in #93 and this issue now tracks the implementation of a higher / broader diagram / chart.

**Comment by marshymarsh** [comment]
this has been addressed with #256
