### ISSUE TITLE
feat: TWAP tutorial

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/docs#126]
### Problem

We are creating tutorials for all basic order types the our main UI provides, but TWAP

### Suggested solution

Add TWAP

### Alternatives considered

Consider TWAP not a core protocol order type and therefore don't create a tutorial, but that seems wrong to me.

### Additional context

We might already have a [medium guide](https://blog.cow.fi/how-to-use-cow-swaps-twap-orders-via-safe-wallet-1a0854484dfb) for this

### Acceptance criteria

Have a nice TWAP tutorial page next to Limit Orders and Swaps

**Comment by alfetopito** [comment]
This was implemented on https://github.com/cowprotocol/docs-v2/pull/163, right?
Already visible at: https://beta.docs.cow.fi/cow-protocol/tutorials/cow-swap/twap

**Comment by mfw78** [comment]
@alfetopito #242 applies some editorial changes to align the tutorial with the others
