### ISSUE TITLE
feat: use new solvers schema for driver <> solver_engine interface

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/docs#139]
### Problem

The legacy `instance.json` format is terribly redundant, full of inconsistencies and unnecessary fields and was refactored during the solver-driver colocation project in favour of a new/cleaner interface between driver and solver_engines (https://github.com/cowprotocol/services/blob/a72c4c374afea785929a0a0a98d7840faf3df34c/crates/solvers/openapi.yml)

### Suggested solution

Explain the problem/result file in terms of the new data model and mark the existing document as deprecated (or remove altogether)

### Alternatives considered

Keep maintaining the old json (but I think that's a bad idea)

**Comment by mfw78** [comment]
In regards to scoping for this, would this be a joint effort between backend and solvers?

**Comment by fleupold** [comment]
I think it should be driven by the solver team with the backend team providing clarification and help where needed. The interface itself is documented using swagger (and in code).
Maybe @fhenneke's test solver from dappcon could be adopted to work with the new interface.

**Comment by fhenneke** [comment]
One thing blocking me from changing the documentation is that the code and api specification for the new interface are inconsistent, see [this issue](https://github.com/cowprotocol/services/issues/2182).
I suppose the rust code is the reference then. But I am not familiar enough with it to derive the format of request and response.
