### ISSUE TITLE
feat: document known smart contract issues

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/docs#147]
### Problem

We have a bunch of known low pri smart contract issues that should be mentioned to avoid confusion with potential bug bounty claims. Namely

- [x] ERC1271 replay for poor smart contract implementations
  - [x] Port [security-related page](https://github.com/cowprotocol/docs/commit/89799d70c4624f9b3aa516dbf4caf92448e497c0) to new docs
- [x] domain_verifier is not "fork-proof" (e.g. the ETHPOW settlement contract, has the same verifier as mainnet)
- [x] Missing security notes on `sellAmount` / `buyAmount` = 0

**Comment by fleupold** [comment]
I saw a PR regarding this. Has this been merged? Can it be closed?

**Comment by mfw78** [comment]
#229 is still open for comment 🙂
