### ISSUE TITLE
bug: `BONUS: Show link to Explorer` comes before pages for creating the order

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/docs#153]
### Problem

This page in the tutorial only makes sense after the order was created so it should come at the end instead of right at the start of `Sign and Post orders Tutorial`

**Comment by alfetopito** [comment]
It seems to be already at the end

![Image](https://github.com/cowprotocol/docs-v2/assets/43217/e42bac3a-c68d-4780-a8d5-e5eb35db2fb1)

Unless you mean something else?

**Comment by MartinquaXD** [comment]
Yeah, looks good now.
I think this also got fixed in https://github.com/cowprotocol/docs-v2/pull/204.
