### ISSUE TITLE
Why is the CoW Protocol main page entitled "CoW Protocol (Batch Auctions)"?

### ISSUE THREAD

**Issue by MindyCoW** [cowprotocol/docs#164]
I have a couple of issues with the header of this page.

1) A CoW Swap user looking for more info about how CoW Swap works might find the "batch auctions" language too jargony & misleading right off the bat.
2) "CoW Protocol (Batch Auctions)" potentially implies that CoW Protocol can be summed up by "batch auctions," when in fact there's more to it. 

I would prefer to have the title be simply "CoW Protocol."

https://github.com/cowprotocol/docs-v2/blob/ba79286ac0c79e89661f9beff4d4d960ea55ec7d/docs/cow-protocol/README.mdx#L1C1-L1C32

**Comment by mfw78** [comment]
Fixed in #188
