### ISSUE TITLE
Maybe don't refer to pending orders as "intents" in Tutorial docs

### ISSUE THREAD

**Issue by MindyCoW** [cowprotocol/docs#168]
For technical & concept sections it's fine, but a user who's at the level of reading a step-by-step tutorial for how to cancel an order on CoW Swap is probably going to be confused by our use of "intents" on this page.

Recommend changing all instances of "intent" to "order," including in the imported snippet.

https://github.com/cowprotocol/docs-v2/blob/a430ab26b52a2f157cf08b8fbcc0b8e190be512d/docs/cow-protocol/tutorials/cow-swap/cancel.mdx#L15-L21

**Comment by mfw78** [comment]
Sure, this sounds like a great idea. What we can do is then link the first instance of "order" to the definitions in the Technical Reference (if they so choose to go down the rabbithole), where the equivalence of intent and order is highlight.

**Comment by mfw78** [comment]
Thinking about this a little more, I'm not so sure about orders vs intent. Using "orders" may specifically indicate to a user that they have an assured outcome (where, actually, the order itself may not actually settle).

**Comment by MindyCoW** [comment]
In the UI, we consistently use "order" to refer to orders/intents that are in flight. 

<img width="77" alt="image" src="https://github.com/cowprotocol/docs-v2/assets/104489816/fb24802b-fdd3-431d-88f0-a36a8f03081f">

We have never referred to these as "intents" in any user-facing context.

**Comment by mfw78** [comment]
OK, fair point. I'll scope the intents --> orders for this to the CoW Swap tutorials specifically.
