### ISSUE TITLE
Aren't DAI and xDAI not the same thing?

### ISSUE THREAD

**Issue by MindyCoW** [cowprotocol/docs#170]
Article refers to the native token of Gnosis Chain as "DAI (xDAI)" and I'm not sure that's correct? xDAI is pegged to DAI but a separate asset, no?

https://github.com/cowprotocol/docs-v2/blob/a430ab26b52a2f157cf08b8fbcc0b8e190be512d/docs/cow-protocol/tutorials/cow-swap/native.mdx#L9

**Comment by mfw78** [comment]
They are not, xDAI is the native currency that is used on the Gnosis Chain blockchain. xDAI is collateralized by DAI on Ethereum Mainnet.

So, DAI is the "canonical" token (ie. what can generally be redeemed at the root for other assets / collateral), and xDAI is somewhat "synthetic", however is backed at least 1:1 by DAI on Ethereum mainnet :smile:

**Comment by MindyCoW** [comment]
I changed "DAI" to "xDAI" in the relevant docs page.

**Comment by mfw78** [comment]
Merged.
