### ISSUE TITLE
chore: verify / reconsider use of "auctioneer"

### ISSUE THREAD

**Issue by MindyCoW** [cowprotocol/docs#183]
There's no previous definition or contextual information explaining what the "auctioneer" is. Is it a centralized piece of code run by CoW Protocol? A decentralized algorithm? A little man with a gavel?

https://github.com/cowprotocol/docs-v2/blob/a430ab26b52a2f157cf08b8fbcc0b8e190be512d/docs/cow-protocol/concepts/introduction/flow-of-an-order.md?plain=1#L23

**Comment by mfw78** [comment]
![image](https://github.com/cowprotocol/docs-v2/assets/53399572/03afaa1c-31e4-4231-8c4f-90dcf7503597)
