### ISSUE TITLE
chore: solvers need the credit

### ISSUE THREAD

**Issue by marshymarsh** [cowprotocol/docs#186]
This sentence is not really accurate:

> CoW Protocol matches users' intents via batch auctions from a variety of on-chain liquidity sources and private market makers.

The batch auctions are between solvers. The solvers find the most-optimal routes from a variety of on-chain liquidity sources and private market makers. 

https://github.com/cowprotocol/docs-v2/blob/a430ab26b52a2f157cf08b8fbcc0b8e190be512d/docs/cow-protocol/README.mdx#L3

**Comment by mfw78** [comment]
FYI, I don't think this is an issue, and the statement is fine, especially from a top-level point in documentation

**Comment by harisang** [comment]
Yeah I also feel this is fine as a high-level statement, so I would suggest we leave it as is and close the issue.
