### ISSUE TITLE
chore: Redo the outline for the concepts section

### ISSUE THREAD

**Issue by marshymarsh** [cowprotocol/docs#191]
As follows:

# What is CoW Protocol?
### Why Batch Auctions? 
(Thesis statement)
### Coincidence of Wants
- ### Types of CoWs
### Intent-based Trading
- ### Market Orders
- ### Limit Orders
- ### TWAP Orders
- ### Smart Orders
- ### Programmatic Orders
- ### --- _Programmatic Order Framework_
- ### Milkman Orders
- ### CoW Hooks
### Additional benefits
# Tutorials
# Technical Reference
# Get Involved
### Grants

https://github.com/cowprotocol/docs-v2/blob/e851b2b831fdea12a90b3d0a47aaea71f98e53ad/docs/cow-protocol/concepts/introduction/protocol-vs-swap.md?plain=1#L1

**Comment by mfw78** [comment]
I'd strongly advise that large rewrites / structural changes are broken down into a more atomic level, to facilitate easier review. It's already difficult to get reviews, let's try make it a little easier :smile:

**Comment by mfw78** [comment]
Broadly related issues:
* #96 
* #95
* #90
* #71
* #63

**Comment by mfw78** [comment]
Closed with merger of #256
