### ISSUE TITLE
feat: orderbook documentation

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/docs#208]
### Problem

#41 captures documenting the autopilot, driver and solver-engine (as well as a high level overview), but it's missing the orderbook service.

### Suggested solution

Add a page for the Orderbook service as well

**Comment by mfw78** [comment]
In addition to the API, which we have published for the order book, are there any notable implementation specific issues / constraints that are desired to be published?

**Comment by fleupold** [comment]
Yes, I think we should document how the API populates the database consumed by the autopilot and include some more details around how quoting works under the hood.
