### ISSUE TITLE
This should go in the "concepts" section

### ISSUE THREAD

**Issue by marshymarsh** [cowprotocol/docs#215]
https://github.com/cowprotocol/docs-v2/blob/0f0bed9d5e5d400406318fce2e922e282a792dc6/docs/cow-protocol/tutorials/arbitrate/README.mdx#L1

**Comment by mfw78** [comment]
As covered in a call, this section refers to components of a system (which is our concrete implementation of batch auctions), and does not pertain to the _concept_ of batch auctions). i.e. one can implement a batch auction system without these explicit components.
