### ISSUE TITLE
This page is titled "arbitrating auctions" but it doesnt tell us anything about arbitrating auctions ... it is a definitions page

### ISSUE THREAD

**Issue by marshymarsh** [cowprotocol/docs#216]
https://github.com/cowprotocol/docs-v2/blob/0f0bed9d5e5d400406318fce2e922e282a792dc6/docs/cow-protocol/tutorials/arbitrate/README.mdx#L20C1-L21C1

**Comment by mfw78** [comment]
This area is a heavy WIP with multiple PRs currently in flight, refer: #207 #41.
