### ISSUE TITLE
chore: wrap cancel part of tutorials into specific order types

### ISSUE THREAD

**Issue by marshymarsh** [cowprotocol/docs#221]
It is confusing that we have a cancel section under "CoW Swap" in tutorials, but then we also have special instructions for how to cancel TWAP orders in-line within the TWAP section, which is at the same heirarchy as the Cancel section. Right now my expectation would be that the Cancel section would tell me how to cancel all orders. Or that each order section would have its own set of cancellation instructions. 

https://github.com/cowprotocol/docs-v2/blob/0f0bed9d5e5d400406318fce2e922e282a792dc6/docs/cow-protocol/tutorials/cow-swap/cancel.mdx#L8C1-L9C1

**Comment by mfw78** [comment]
There are actually _some_ differences, and they actually are in different sections of the UI. It does seem fair to wrap the Cancel section into the relative Swap / Limit / Native / TWAP sections.

**Comment by mfw78** [comment]
Before I assign this, can we get some weigh-in from @MindyCoW, @anxolin, and perhaps @fleupold as to if this seems sound?

**Comment by MindyCoW** [comment]
Makes sense to me.

**Comment by anxolin** [comment]
I was finding it OK, as SWAP is the primary thing a user would do in CoW Swap. 
I find it also ok, to keep CANCEL separated from the SWAP tutorial, so is more lean this important flow.

Limit Orders and TWAP I feel are more advanced, so I find ok they are self-contained. Note how the UI is also self-contained so you see the orders next to the widget as opposed to in SWAP, so it feels right to be together. 

So I would leave it as it is. Maybe just add a section at the end of CANCEL saying:
See also:
- Cancelation for Limit Orders
- Cancelation for TWAP
- ..and even links to cancelation using Etherscan! (or pointing how to do it in the the smart contract and API)

**Comment by anxolin** [comment]
Since we are at it, do we see a problem with:

<img width="275" alt="image" src="https://github.com/cowprotocol/docs-v2/assets/2352112/75b2a2eb-8da4-4747-bb02-44859663ef56">

**Comment by mfw78** [comment]
Yep, for the tutorials section, I've been inclined towards trying to stick to verbs "I want to _do_ something", but this isn't straightforward when talking about different aspects of CoW Swap.
