### ISSUE TITLE
feat: Make Safe specific Tutorials: approve + swap, eth-flow for safe

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/docs#228]
### Problem
CoW Swap has some nice Safe functions we could make a tutorial for.

### Suggested solution
- [ ] Safe Swap: Bundle approve and swap
- [ ] Safe ETH Flow: Bundle wrapping

**Comment by mfw78** [comment]
Great idea. I think within the respective (Swap / Native) tutorials, we can add `Safe` specific sections, or Tips / Notes. I'd be cautious around full/separate tutorials as these may run the risk of duplication of content.

**Comment by alfetopito** [comment]
I'll add them to the existing tutorials as per comment.
