### ISSUE TITLE
chore: Should the core part of the solver competition specifications explicitly distinguish between general rules and rules that apply only on mainnet?

### ISSUE THREAD

**Issue by harisang** [cowprotocol/docs#231]
I just realized that the whole solver competition mechanism part  assumes we are talking about mainnet. Although i think it is fine for now, we do, for example, also run batch auctions on Gnosis Chain (and hope to expand in other chains as well). Do you think it's worth adding a few sentences here and there to clarify things and distinguish between different chains?

cc @fleupold @mfw78

**Comment by mfw78** [comment]
Is this a difference that's already covered by the CIPs? If so, I think we can just put a "note" admonition that lets the reader know they should drill down into the CIPs for chain specific (or perhaps have a table by CIP and chain to show which is implemented where).

If it's not in a CIP, I think the explanation should be a little longer as to why the difference between main get and the respective chain exists. Thoughts?

**Comment by harisang** [comment]
Yeah unfortunately the CIPs were written with the assumption we are only talking about mainnet; however within the CIPs' text, this is not made explicit.

I think it makes sense to add some clarification stating that solver rewards and slippage accounting apply only on mainnet. Will create a PR to take care of this now.

**Comment by fleupold** [comment]
Agree, the goal of these docs is to not require people to read through a handful of CIPs and mentally apply the rules on top of one another to get to a holistic conclusion. Let's add details for non mainnet rules.

**Comment by fleupold** [comment]
Agree, the goal of these docs is to not require people to read through a handful of CIPs and mentally apply the rules on top of one another to get to a holistic conclusion. Let's add details for non mainnet rules.

**Comment by mfw78** [comment]
(duplicate comment deleted)
