### ISSUE TITLE
bug: Notify endpoint (again...)

### ISSUE THREAD

**Issue by harisang** [cowprotocol/docs#232]
I noticed we have this section in the solver-related tutorials.

`https://beta.docs.cow.fi/cow-protocol/tutorials/solvers/evaluate`

Should we just remove this, or at least say that solvers live in prod/staging can use the endpoint instead to get notified about who won the auction, the moment the auction closes?

**Comment by mfw78** [comment]
Up to you guys if you want to kill it or not. I just ported this as it's what I saw in the old docs.

**Comment by mfw78** [comment]
Related to #43
