### ISSUE TITLE
bug: no top/bottom padding after an <Image>

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/docs#241]
### Problem

Seems like <Image> components have no padding on top/bottom

### To reproduce

If you can reproduce the behaviour, steps to reproduce:

1. Add and `<Image>` element
2. After it, add a `:::tip` block
3. Visit the page where the image is followed by the tip block

### Expected behaviour

There should be some padding after the image

### Screenshots/logs

Using the `<Image>` tag, followed by a `:::tip`

![image](https://github.com/cowprotocol/docs-v2/assets/43217/66a2aac3-99f5-4d75-8251-901c105da2d7)

The same, replacing `<Image>` with native `![alt](/localtion)` markdown notation

![image](https://github.com/cowprotocol/docs-v2/assets/43217/27cd2d52-d5c7-4fbd-9d95-592b9b44171b)

### docs version/commit hash

First noticed on this commit 16b485fc334da64cd246f783753033563710d8f1

### Additional context

Discussion initiated [in this thread](https://cowservices.slack.com/archives/C04N05LJK54/p1702922460712259)

**Comment by anxolin** [comment]
Ideally we add the label so it shows in the kanban when we filter by our team
