### ISSUE TITLE
chore: sepolia address for core and peripheral contracts

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/docs#262]
### Background

We've added a new network, so this needs to be documented :rocket: 

### Details

With the deployment of CoW Protocol on Sepolia, these networks should be documented in the Technical Reference --> Contracts section (both for `Core` and `Peripheral` contracts that have been deployed.

### Acceptance criteria

- [x] Core contracts listing updated.
- [ ] Peripheral contracts listing updated.

**Comment by fedgiac** [comment]
Once #264 is merged, this issue can be closed by adding the address for `ComposableCoW`. As of now, this contract is not available on Sepolia.
