### ISSUE TITLE
[Docs] Document URL parameters

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/docs#341]
# Summary

We used to have documentation for URL parameters but it got lost at some point.

Add documentation for all supported parameters, which are:

- `sellAmount`
- `buyAmount`
- `receiver`

Also mention the context on how they are loaded.

Namely, on SWAP, either `sellAmount` or `buyAmount` values are expected. When both are set, `sellAmount` is used.
While on LIMIT`, both are accepted and this in turn is used to set the limit price.

**Comment by fleupold** [comment]
We should also document the different ways to specify the pair and chain (Symbol vs addresses)

Not the right repo I know, but could we also make appData pass-able?

**Comment by alfetopito** [comment]
Turns out we do have it already, but it's not yet published for some reason https://github.com/cowprotocol/docs/blob/ab8d7fbe72489af9f4b0f6d2cf0c3cd35be6c76a/docs/cow-protocol/tutorials/cow-swap/custom-links.md

**Comment by alfetopito** [comment]
> Not the right repo I know, but could we also make appData pass-able?

You mean to document the appData in the docs?
Or to allow the appData to be set from the url?

**Comment by fleupold** [comment]
> Or to allow the appData to be set from the url?

This ☝️

**Comment by alfetopito** [comment]
> > Or to allow the appData to be set from the url?
> 
> This ☝️

https://github.com/cowprotocol/cowswap/issues/4107

**Comment by alfetopito** [comment]
Addressed on https://github.com/cowprotocol/docs/pull/344
