### ISSUE TITLE
what is a Merkle bid? Why all of a sudden we bring it up?

### ISSUE THREAD

**Issue by acanidio-econ** [cowprotocol/docs#371]
https://github.com/cowprotocol/docs/blob/01b0d1b6ad60eabd35173a3c7f7519f66df990cc/docs/mevblocker/searchers/bidding-on-transactions.md?plain=1#L9

**Comment by cmagan** [comment]
I don't know what Merkle bid is (:
Maybe it's a typo and should be: MEV Blocker bid?

**Comment by acanidio-econ** [comment]
I changed the text to remove "merkle bid"
