### ISSUE TITLE
feat: Cookbook Onboard (AI Assistant) integration

### ISSUE THREAD

**Issue by ClockRide** [cowprotocol/docs#406]
The AI assistant and co-pilot is trained on all existing CoW Protocol resources (source code, docs website, etc) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about using CoW Protocol, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity coding co-pilot.

Ask Cookbook AI could also access context from thousands of data sources indexed by Cookbook.dev in addition to CoW DAO-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.

## Preview
https://cow-docs-cookbook.vercel.app/

![image](https://github.com/user-attachments/assets/0d07348c-1cc9-4d4b-80ac-70e8a38edb0d)

**Comment by mfw78** [comment]
Closed per #407
