### ISSUE TITLE
chore: Make links stand out visually

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/docs#45]
### Background

The docs are super nice and use links to get you to places with more info on some topics but because links are only identifiable as such by hovering over them you can probably not notice lots of links.
Basically you currently have to hover over every word in order to not miss any links.

### Acceptance criteria

Links are immediately identifiable as such (or at least you should not have to hover over them to detect them).

**Comment by fairlighteth** [comment]
Is this issue still relevant? This is how links currently are rendered:

---

![Image](https://github.com/cowprotocol/docs-v2/assets/31534717/f39a175d-6f12-4212-bd8c-49fb5a0ffb80)

![Image](https://github.com/cowprotocol/docs-v2/assets/31534717/0049c587-c0c1-42ea-8ee0-d1725e9c6e95)
