### ISSUE TITLE
Links to be fixed

### ISSUE THREAD

**Issue by crystalmacow** [cowprotocol/docs#50]
Links to be fixed for "MEV Blocker", "CoW Grants Program, the CoW Protocol Explorer, and the CoW Swap frontend"

https://github.com/cowprotocol/docs-v2/blob/763167a3ce1e9438525dbdf0b5b4d58e02575194/docs/README.md?plain=1#L10C49-L10C49

**Comment by mfw78** [comment]
Thanks, will make sure that this is fixed for prod
