### ISSUE TITLE
bug: Flow-of-an-order incorrect diagram

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/docs#67]
https://github.com/cowprotocol/docs-v2/blob/2bda7a60d5f3b26e8dd6fcbedcd45294ba72498b/docs/cow-protocol/concepts/introduction/flow-of-an-order.md?plain=1#L13

The diagram is missing the fact that solvers report a score back to the auctioneer and the auctioneer tells the winning driver to execute. Moreover, the settlement isn't executed by the solver engine but by the driver component direclty.

**Comment by mfw78** [comment]
Additionally, as per @marshymarsh / @MindyCoW (with general consensus beyond these), we removed the term "auctioneer" and can be just thought of as "The Protocol".

**Comment by marshymarsh** [comment]
this has been addressed with #256
