### ISSUE TITLE
are solvers "trusted third parties"?

### ISSUE THREAD

**Issue by acanidio-econ** [cowprotocol/docs#72]
In the introductory part of the documentation, we refer to solvers as "trusted third parties"

https://github.com/cowprotocol/docs-v2/blob/ee6f5a7e84d20416a1e350a32014fce1ebee02fb/docs/cow-protocol/concepts/introduction/solvers.md?plain=1#L7

They may be now because they are KYCd but the goal is to move to a decentralized/trustless set up (in the sense that misbehaving is prevented by the threat of slashing). I would therefore remove "trusted"

**Comment by mfw78** [comment]
This has been amended to refer to solvers as "bonded" parties to reflect their nature within CoW Protocol's design.
