### ISSUE TITLE
drop the graph

### ISSUE THREAD

**Issue by acanidio-econ** [cowprotocol/docs#93]
This graph;

https://github.com/cowprotocol/docs-v2/blob/6c6e7477506a4ac2d709042ece80ef2e1b4ef0ed/docs/cow-protocol/concepts/batch-auctions/how-batch-auctions-work.md?plain=1#L11

is not discussed in the text of the page. And without discussion, it is impossible to understand what it represents (what is an autopilot?, what is driver0 and driver1?). It feels misplaced: I suggest dropping it or moving it to the technical references

**Comment by mfw78** [comment]
Related #64

**Comment by mfw78** [comment]
This has been dropped. #104 is open to replace the sequence diagram.
